# Generated by Django 6.0.2 on 2026-02-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('REVIEWED', 'Reviewed'), ('REJECTED', 'Rejected'), ('HIRED', 'Hired')], default='APPLIED', max_length=20)),
                ('responses', models.JSONField(blank=True, default=dict)),
                ('extra_attachment', models.FileField(blank=True, null=True, upload_to='application_docs/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
