# Generated by Django 5.2.11 on 2026-02-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
